name: UltraEssentials
main: LUKAY\UltraEssentials\Loader
author: LUKAY
api: 5.0.0
version: 0.0.6
permissions:
  ultraessentials.deletehome.command:
    default: true
  ultraessentials.home.command:
    default: true
  ultraessentials.homes.command:
    default: true
  ultraessentials.sethome.command:
    default: true
  ultraessentials.tpa.command:
    default: true
  ultraessentials.tpahere.command:
    default: true
  ultraessentials.tpaccept.command:
    default: true
  ultraessentials.tpadecline.command:
    default: true
  ultraessentials.tpall.command:
    default: op
  ultraessentials.vanish.command:
    default: op
  ultraessentials.unvanish.command:
    default: op
  ultraessentials.see.vanished:
    default: op