name: UltraEssentials
main: LUKAY\UltraEssentials\Loader
author: LUKAY
api: 5.0.0
version: 0.1.0
permissions:
  ultraessentials.account.command:
    default: op
  ultraessentials.deletehome.command:
    default: true
  ultraessentials.home.command:
    default: true
  ultraessentials.homes.command:
    default: true
  ultraessentials.sethome.command:
    default: true
  ultraessentials.unlimited.homes:
    default: op
  ultraessentials.tpa.command:
    default: true
  ultraessentials.tpahere.command:
    default: true
  ultraessentials.tpaccept.command:
    default: true
  ultraessentials.tpadecline.command:
    default: true
  ultraessentials.tpall.command:
    default: op
  ultraessentials.feed.command:
    default: op
  ultraessentials.feed.others.command:
    default: op
  ultraessentials.heal.command:
    default: op
  ultraessentials.heal.others.command:
    default: op
  ultraessentials.nick.command:
    default: op
  ultraessentials.unick.command:
    default: op
  ultraessentials.unick.others.command:
    default: op
  ultraessentials.vanish.command:
    default: op
  ultraessentials.vanish.others.command:
    default: op
  ultraessentials.unvanish.command:
    default: op
  ultraessentials.unvanish.others.command:
    default: op
  ultraessentials.see.vanished:
    default: op